[package]
name = "open_dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tui]
version = "0.19"

[dependencies.crossterm]
version = "0.25"
